### ISSUE TITLE
Eroare dupa selectarea judetului in pasul de livrare

### ISSUE THREAD

**Issue by marmureanuweb** [infifni/sylius-fan-courier-plugin#1]
"Vă rugăm să alegeți un judeţ corespunzător." Chiar daca judetul este selectat, el nu este trimis prin POST.
Mai mult de atat, daca incerci sa editezi un judet, in admin este aruncata urmatoare eroare la salvare -> "Codul provinciei ar trebui să aibă următorul format XX-XX (ex. RO-BV)."

**Comment by laurentiu-cocos** [comment]
De trimis prin POST nu am vazut sa fie problema, nu stiu exact care este contextul tau.
Faza cu codurile stiam de ea, va fi schimbat la livrarea primei versiuni stabile, modulul de fata inca nu se poate folosi decat numai pentru estimare. Daca vrei sa scapi de erorile din admin temporar schimba ce se insereaza pentru abreviere cu ceea ce se insereaza pentru cod.

**Comment by laurentiu-cocos** [comment]
Am mai push-uit un set de commits, unde query-urile corecte le poti gasi in singura migrare.

**Comment by laurentiu-cocos** [comment]
Am sa inchid acest issue, eu cred ca s-a rezolvat cu ultimul set de commits, daca nu am sa te rog sa-l redeschizi (astazi am push-uit si generarea de AWB).
